# Generated by Django 4.2.30 on 2026-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Oyuncu bekleniyor'), ('SETTING_NUMBERS', 'Gizli sayılar giriliyor'), ('IN_PROGRESS', 'Devam ediyor'), ('FINISHED', 'Bitti'), ('ABANDONED', 'Terk edildi')], default='WAITING', max_length=20),
        ),
    ]
