# Generated by Django 4.2.30 on 2026-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_guess_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for players'), ('CHOOSING', 'Choosing characters'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='WAITING', max_length=20),
        ),
    ]
