# Generated by Django 4.2.30 on 2026-09-30 15:40

from django.db import migrations, models
import django.db.models.deletion
import game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_identifier', models.CharField(max_length=100, unique=True)),
                ('secret_number', models.CharField(max_length=4, validators=[game.models.validate_four_digit_unique])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
                ('turn_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=4, validators=[game.models.validate_four_digit_unique])),
                ('result', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn_number', models.IntegerField()),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for players'), ('SETTING_NUMBERS', 'Setting secret numbers'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_in', to='game.gameplayer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='game.gameplayer')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameroom'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game_room', 'turn_order')},
        ),
    ]
