# Generated by Django 5.2.16 on 2026-10-06 11:17

import django.db.models.deletion
import satranc.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_identifier', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('w', 'Beyaz'), ('b', 'Siyah')], max_length=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Oyuncu bekleniyor'), ('IN_PROGRESS', 'Devam ediyor'), ('FINISHED', 'Bitti'), ('ABANDONED', 'Terk edildi')], default='WAITING', max_length=20)),
                ('fen', models.CharField(default=satranc.models.initial_fen, max_length=100)),
                ('result', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='satranc.gameplayer')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='satranc.gameroom'),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uci', models.CharField(max_length=5)),
                ('san', models.CharField(max_length=12)),
                ('fen_after', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='satranc.gameroom')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='satranc.gameplayer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game_room', 'color')},
        ),
    ]
