# Generated by Django 5.2.16 on 2026-10-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satranc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
