# Generated by Django 4.2.30 on 2026-10-05 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_identifier', models.CharField(max_length=100, unique=True)),
                ('character_id', models.CharField(blank=True, default='', max_length=64)),
                ('eliminated', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for players'), ('CHOOSING', 'Choosing characters'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awaiting_answer', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_in', to='kim.gameplayer')),
                ('question_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_questions', to='kim.gameplayer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='kim.gameplayer')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='kim.gameroom'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Chat'), ('question', 'Question'), ('answer', 'Answer'), ('system', 'System')], default='chat', max_length=10)),
                ('text', models.TextField()),
                ('answer', models.CharField(blank=True, default='', max_length=3)),
                ('reply_to', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='kim.gameplayer')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='kim.gameroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Accusation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_id', models.CharField(max_length=64)),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accusations', to='kim.gameplayer')),
            ],
        ),
    ]
